sudo: required
services:
  - docker

script:
  - docker build -t andrewtdunn28/react-example2 .
  - docker images andrewtdunn28/react-example2

before_deploy:
  - docker login -u andrewtdunn28 -p s@mples@mple

deploy:
  provider: script
  script: docker push andrewtdunn28/react-example2
  on:
    branch: master
